WIP 6

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -22,30 +22,9 @@ stages:
   - echo 'deb http://deb.debian.org/debian sid main' > /etc/apt/sources.list
   # Upgrade minimal stack first
   - apt-get update -qq
-  - curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/g/glibc/libc6_2.38-11_amd64.deb
-  - curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/g/glibc/libc-bin_2.38-11_amd64.deb
-  - apt-get -q install --no-install-recommends --yes ./libc6_2.38-11_amd64.deb ./libc-bin_2.38-11_amd64.deb || export APT_STATUS="failed"
-  # Ensure upgrades past 2.38-11 are blocked so tests don't fail on usrmerge issues
-  - apt-mark hold libc6 libc-bin
-  # Due to https://bugs.debian.org/993755 and #975077 upgrades from Buster or
-  # older to Bookworm or newer always fails on:
-  #   /usr/bin/perl: error while loading shared libraries: libcrypt.so.1: cannot
-  #     open shared object file: No such file or directory
-  #   dpkg: error processing package libc6:amd64 (--configure):
-  # Therefore, run this extra workaround if first run of apt-get install failed:
-  - |
-    if [ "$APT_STATUS" = "failed" ]
-    then
-      cd $(mktemp -d) # Use temp dir where apt can download and unpack files
-      apt-get -y download libcrypt1
-      dpkg-deb -x libcrypt1_*.deb .
-      cp -ra usr/lib/* /lib/ || true # libcrypt 1:4.4.36-3+
-      cd - # Back to /builds/$USER/mariadb-server/debian/output
-      find /lib/*/libcrypt.* -ls # Show that new libcrypt is there
-      apt-get -q --yes --fix-broken install
-    fi
-  - apt-get -q install apt || export SECOND_APT_STATUS="failed"
-  # Upgrades from Bullseye or older to Trixie or newer always fail on:
+  # Complete upgrade of minimal stack
+  - apt-get install -q --yes apt || export APT_STATUS="failed"
+  # Upgrades from Bullseye (or older) to Trixie (or newer) will pull in base-files 13.4+, which will always fail on:
   #   Preparing to unpack .../base-files_13.4_amd64.deb ...
   #   ******************************************************************************
   #   *
@@ -59,15 +38,45 @@ stages:
   #   ******************************************************************************
   # Therefore, run this older base-files must be used:
   - |
-    if [ "$SECOND_APT_STATUS" = "failed" ]
+    if [ "$APT_STATUS" = "failed" ]
     then
       curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/b/base-files/base-files_13.2_amd64.deb
-      apt-get -q install --no-install-recommends --yes ./base-files_13.2_amd64.deb
+      apt-get -q --yes --no-install-recommends install ./base-files_13.2_amd64.deb
       # Ensure upgrades past 13.2 are blocked so tests don't fail on usrmerge issues
       apt-mark hold base-files
+      apt-get -q --yes --fix-broken install apt
+    fi || export BASE_FILES_STATUS="failed"
+  # libc6 : Breaks: base-files (< 13.3~) but 13.2 is to be installed
+  - |
+    if [ "$BASE_FILES_STATUS" = "failed" ]
+    then
+      curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/g/glibc/libc6_2.38-11_amd64.deb
+      curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/g/glibc/libc-bin_2.38-11_amd64.deb
+      apt-get -q install --no-install-recommends --yes ./libc6_2.38-11_amd64.deb ./libc-bin_2.38-11_amd64.deb
+      # Ensure upgrades past 2.38-11 are blocked so tests don't fail on usrmerge issues
+      apt-mark hold libc6 libc-bin
+      apt-get -q --yes --fix-broken install apt
+    fi || export LIBC_STATUS="failed"
+  # Due to https://bugs.debian.org/993755 and #975077 upgrades from Buster or
+  # older to Bookworm or newer always fails on:
+  #   /usr/bin/perl: error while loading shared libraries: libcrypt.so.1: cannot
+  #     open shared object file: No such file or directory
+  #   dpkg: error processing package libc6:amd64 (--configure):
+  # Therefore, run this extra workaround if first run of apt-get install failed:
+  - |
+    if [ "$LIBC_STATUS" = "failed" ]
+    then
+      cd $(mktemp -d) # Use temp dir where apt can download and unpack files
+      apt-get -y download libcrypt1
+      dpkg-deb -x libcrypt1_*.deb .
+      cp -ra usr/lib/* /lib/ || true # libcrypt 1:4.4.36-3+
+      cd - # Back to /builds/$USER/mariadb-server/debian/output
+      find /lib/*/libcrypt.* -ls # Show that new libcrypt is there
+      apt-mark unhold libc6 libc-bin
+      apt-get -q --yes --fix-broken --no-install-recommends install ./libc6_2.38-11_amd64.deb ./libc-bin_2.38-11_amd64.deb
+      apt-mark hold libc6 libc-bin
+      apt-get install -q --yes apt
     fi
-  # Complete upgrade of minimal stack
-  - apt-get install -q --yes apt
 
 .test-enable-plain-sid-repos: &test-enable-plain-sid-repos
   - apt-get install -qq --yes --no-install-recommends ca-certificates curl
@@ -129,11 +138,12 @@ upgrade from jessie:
   script:
     - |
       cat > /etc/apt/sources.list <<EOF
-      deb http://archive.debian.org/debian jessie main
-      deb http://archive.debian.org/debian-security jessie/updates main
+      # Trust blindly as Jessie key expired and will not be renewed
+      deb [trusted=yes] http://archive.debian.org/debian jessie main
+      deb [trusted=yes] http://archive.debian.org/debian-security jessie/updates main
       EOF
     - *test-prepare-container
-    - apt-get install -y --force-yes entr
+    - apt-get install -y entr
     - *test-enable-sid-repos
     - apt-get install -y entr
 
@@ -185,10 +195,11 @@ plain upgrade from jessie:
   script:
     - |
       cat > /etc/apt/sources.list <<EOF
-      deb http://archive.debian.org/debian jessie main
-      deb http://archive.debian.org/debian-security jessie/updates main
+      # Trust blindly as Jessie key expired and will not be renewed
+      deb [trusted=yes] http://archive.debian.org/debian jessie main
+      deb [trusted=yes] http://archive.debian.org/debian-security jessie/updates main
       EOF
     - *test-prepare-container
-    - apt-get install -y --force-yes entr
+    - apt-get install -y entr
     - *test-enable-plain-sid-repos
     - apt-get install -y entr
